name: Auto Dependabot
on:
  pull_request

jobs:
  auto-approve:
    name: Approve
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@a3e5f86ae9f2f49b441498973ddec20035d326b8 # v1.1.1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Auto-approve for non-npm updates only
        if: ${{ steps.metadata.outputs.package-ecosystem != 'npm' }}
        uses: hmarr/auto-approve-action@44888193675f29a83e04faf4002fa8c0b537b1e4 # v3.2.1
  auto-merge:
    name: Merge after successful checks
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@a3e5f86ae9f2f49b441498973ddec20035d326b8 # v1.1.1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Generate GitHub App token
        if: ${{ steps.metadata.outputs.package-ecosystem != 'npm' }}
        id: app-token
        uses: actions/create-github-app-token@7bfa3a4717ef143a604ee0a99d859b8886a96d00 # v1.9.3
        with:
          app-id: ${{ vars.AUTO_DEPENDABOT_APP_ID }}
          private-key: ${{ secrets.AUTO_DEPENDABOT_APP_PRIVATE_KEY }}
          permission-contents: write
          permission-pull-requests: write
      - name: Enable auto-merge for non-npm Dependabot PRs
        if: ${{ steps.metadata.outputs.package-ecosystem != 'npm' }}
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
